var classes = [
    {
        "name": "Event",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isWithinDayRange",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "ccnMethodMax": 5,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 104,
        "vocabulary": 25,
        "volume": 482.96,
        "difficulty": 14.58,
        "effort": 7043.18,
        "level": 0.07,
        "bugs": 0.16,
        "time": 391,
        "intelligentContent": 33.12,
        "number_operators": 29,
        "number_operands": 75,
        "number_operators_unique": 7,
        "number_operands_unique": 18,
        "cloc": 25,
        "loc": 79,
        "lloc": 54,
        "mi": 80.61,
        "mIwoC": 42.34,
        "commentWeight": 38.26,
        "kanDefect": 0.8,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 8,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Application",
        "interface": false,
        "methods": [
            {
                "name": "middleware",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Cake\\Http\\BaseApplication",
            "Cake\\Routing\\Middleware\\RoutingMiddleware"
        ],
        "parents": [
            "Cake\\Http\\BaseApplication"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 1,
        "effort": 7.92,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 7.92,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 12,
        "loc": 21,
        "lloc": 9,
        "mi": 118.82,
        "mIwoC": 72.76,
        "commentWeight": 46.06,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Shell\\ConsoleShell",
        "interface": false,
        "methods": [
            {
                "name": "main",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOptionParser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Cake\\Console\\Shell",
            "Cake\\Log\\Log",
            "Cake\\Log\\Log",
            "Psy\\Shell",
            "Cake\\Console\\ConsoleOptionParser"
        ],
        "parents": [
            "Cake\\Console\\Shell"
        ],
        "lcom": 2,
        "length": 48,
        "vocabulary": 24,
        "volume": 220.08,
        "difficulty": 3.8,
        "effort": 836.3,
        "level": 0.26,
        "bugs": 0.07,
        "time": 46,
        "intelligentContent": 57.92,
        "number_operators": 10,
        "number_operands": 38,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 13,
        "loc": 47,
        "lloc": 34,
        "mi": 86.3,
        "mIwoC": 49.92,
        "commentWeight": 36.38,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.57,
        "totalSystemComplexity": 72.57,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TeamsUsersController",
        "interface": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Controller\\AppController"
        ],
        "parents": [
            "App\\Controller\\AppController"
        ],
        "lcom": 1,
        "length": 126,
        "vocabulary": 29,
        "volume": 612.11,
        "difficulty": 6.12,
        "effort": 3743.26,
        "level": 0.16,
        "bugs": 0.2,
        "time": 208,
        "intelligentContent": 100.09,
        "number_operators": 20,
        "number_operands": 106,
        "number_operators_unique": 3,
        "number_operands_unique": 26,
        "cloc": 38,
        "loc": 94,
        "lloc": 56,
        "mi": 83.21,
        "mIwoC": 41.54,
        "commentWeight": 41.66,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.24,
        "relativeSystemComplexity": 196.24,
        "totalStructuralComplexity": 980,
        "totalDataComplexity": 1.2,
        "totalSystemComplexity": 981.2,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\ErrorController",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "beforeFilter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "beforeRender",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "afterFilter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Controller\\AppController",
            "Cake\\Event\\Event",
            "Cake\\Event\\Event",
            "parent",
            "Cake\\Event\\Event"
        ],
        "parents": [
            "App\\Controller\\AppController"
        ],
        "lcom": 4,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 28,
        "loc": 47,
        "lloc": 19,
        "mi": 110.06,
        "mIwoC": 63.54,
        "commentWeight": 46.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.15,
        "relativeSystemComplexity": 16.15,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 64.6,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UsersController",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Controller\\AppController",
            "parent"
        ],
        "parents": [
            "App\\Controller\\AppController"
        ],
        "lcom": 1,
        "length": 111,
        "vocabulary": 23,
        "volume": 502.12,
        "difficulty": 6.83,
        "effort": 3426.94,
        "level": 0.15,
        "bugs": 0.17,
        "time": 190,
        "intelligentContent": 73.57,
        "number_operators": 20,
        "number_operands": 91,
        "number_operators_unique": 3,
        "number_operands_unique": 20,
        "cloc": 38,
        "loc": 110,
        "lloc": 72,
        "mi": 78.99,
        "mIwoC": 39.5,
        "commentWeight": 39.49,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 361.27,
        "totalStructuralComplexity": 2888,
        "totalDataComplexity": 2.15,
        "totalSystemComplexity": 2890.15,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\ProjectsController",
        "interface": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assigned",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAuthorized",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Controller\\AppController",
            "Cake\\ORM\\TableRegistry",
            "parent"
        ],
        "parents": [
            "App\\Controller\\AppController"
        ],
        "lcom": 1,
        "length": 115,
        "vocabulary": 26,
        "volume": 540.55,
        "difficulty": 8.45,
        "effort": 4570.11,
        "level": 0.12,
        "bugs": 0.18,
        "time": 254,
        "intelligentContent": 63.94,
        "number_operators": 22,
        "number_operands": 93,
        "number_operators_unique": 4,
        "number_operands_unique": 22,
        "cloc": 42,
        "loc": 108,
        "lloc": 66,
        "mi": 81.37,
        "mIwoC": 40.23,
        "commentWeight": 41.13,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 361.28,
        "totalStructuralComplexity": 2527,
        "totalDataComplexity": 1.95,
        "totalSystemComplexity": 2528.95,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TasksController",
        "interface": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assigned",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAuthorized",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Controller\\AppController",
            "Cake\\ORM\\TableRegistry",
            "Cake\\ORM\\TableRegistry",
            "parent"
        ],
        "parents": [
            "App\\Controller\\AppController"
        ],
        "lcom": 1,
        "length": 156,
        "vocabulary": 32,
        "volume": 780,
        "difficulty": 9.14,
        "effort": 7131.43,
        "level": 0.11,
        "bugs": 0.26,
        "time": 396,
        "intelligentContent": 85.31,
        "number_operators": 28,
        "number_operands": 128,
        "number_operators_unique": 4,
        "number_operands_unique": 28,
        "cloc": 42,
        "loc": 118,
        "lloc": 76,
        "mi": 77.69,
        "mIwoC": 37.78,
        "commentWeight": 39.91,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 361.28,
        "totalStructuralComplexity": 2527,
        "totalDataComplexity": 1.95,
        "totalSystemComplexity": 2528.95,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\AppController",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "beforeRender",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAuthorized",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Cake\\Controller\\Controller",
            "parent",
            "Cake\\ORM\\TableRegistry",
            "Cake\\ORM\\TableRegistry",
            "Cake\\Event\\Event"
        ],
        "parents": [
            "Cake\\Controller\\Controller"
        ],
        "lcom": 3,
        "length": 73,
        "vocabulary": 43,
        "volume": 396.12,
        "difficulty": 4.86,
        "effort": 1927.06,
        "level": 0.21,
        "bugs": 0.13,
        "time": 107,
        "intelligentContent": 81.42,
        "number_operators": 13,
        "number_operands": 60,
        "number_operators_unique": 6,
        "number_operands_unique": 37,
        "cloc": 27,
        "loc": 62,
        "lloc": 35,
        "mi": 90.53,
        "mIwoC": 47.86,
        "commentWeight": 42.67,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 121.22,
        "totalStructuralComplexity": 363,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 363.67,
        "pageRank": 0.35,
        "afferentCoupling": 8,
        "efferentCoupling": 4,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TeamsController",
        "interface": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assigned",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Controller\\AppController",
            "Cake\\ORM\\TableRegistry"
        ],
        "parents": [
            "App\\Controller\\AppController"
        ],
        "lcom": 1,
        "length": 108,
        "vocabulary": 25,
        "volume": 501.54,
        "difficulty": 6.14,
        "effort": 3077.61,
        "level": 0.16,
        "bugs": 0.17,
        "time": 171,
        "intelligentContent": 81.73,
        "number_operators": 18,
        "number_operands": 90,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 41,
        "loc": 100,
        "lloc": 59,
        "mi": 83.51,
        "mIwoC": 41.66,
        "commentWeight": 41.86,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.19,
        "relativeSystemComplexity": 289.19,
        "totalStructuralComplexity": 1734,
        "totalDataComplexity": 1.17,
        "totalSystemComplexity": 1735.17,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\TasksUsersController",
        "interface": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Controller\\AppController"
        ],
        "parents": [
            "App\\Controller\\AppController"
        ],
        "lcom": 1,
        "length": 127,
        "vocabulary": 30,
        "volume": 623.18,
        "difficulty": 5.94,
        "effort": 3704.43,
        "level": 0.17,
        "bugs": 0.21,
        "time": 206,
        "intelligentContent": 104.83,
        "number_operators": 20,
        "number_operands": 107,
        "number_operators_unique": 3,
        "number_operands_unique": 27,
        "cloc": 38,
        "loc": 94,
        "lloc": 56,
        "mi": 83.15,
        "mIwoC": 41.49,
        "commentWeight": 41.66,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.24,
        "relativeSystemComplexity": 196.24,
        "totalStructuralComplexity": 980,
        "totalDataComplexity": 1.2,
        "totalSystemComplexity": 981.2,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\PagesController",
        "interface": false,
        "methods": [
            {
                "name": "display",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAuthorized",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Controller\\AppController",
            "Cake\\Network\\Exception\\ForbiddenException",
            "Cake\\Core\\Configure",
            "Cake\\Network\\Exception\\NotFoundException",
            "parent"
        ],
        "parents": [
            "App\\Controller\\AppController"
        ],
        "lcom": 2,
        "length": 52,
        "vocabulary": 21,
        "volume": 228.4,
        "difficulty": 7,
        "effort": 1598.8,
        "level": 0.14,
        "bugs": 0.08,
        "time": 89,
        "intelligentContent": 32.63,
        "number_operators": 17,
        "number_operands": 35,
        "number_operators_unique": 6,
        "number_operands_unique": 15,
        "cloc": 18,
        "loc": 55,
        "lloc": 37,
        "mi": 87.2,
        "mIwoC": 48.47,
        "commentWeight": 38.74,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.57,
        "relativeSystemComplexity": 36.57,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.14,
        "totalSystemComplexity": 73.14,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Entity\\Team",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Cake\\ORM\\Entity"
        ],
        "parents": [
            "Cake\\ORM\\Entity"
        ],
        "lcom": 0,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 18,
        "loc": 23,
        "lloc": 5,
        "mi": 128.88,
        "mIwoC": 79.88,
        "commentWeight": 49,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Entity\\TasksUser",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Cake\\ORM\\Entity"
        ],
        "parents": [
            "Cake\\ORM\\Entity"
        ],
        "lcom": 0,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 19,
        "loc": 24,
        "lloc": 5,
        "mi": 127.37,
        "mIwoC": 78.29,
        "commentWeight": 49.08,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Entity\\User",
        "interface": false,
        "methods": [
            {
                "name": "_setPassword",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Cake\\ORM\\Entity",
            "Cake\\Auth\\DefaultPasswordHasher"
        ],
        "parents": [
            "Cake\\ORM\\Entity"
        ],
        "lcom": 1,
        "length": 18,
        "vocabulary": 14,
        "volume": 68.53,
        "difficulty": 2.05,
        "effort": 140.18,
        "level": 0.49,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 33.5,
        "number_operators": 3,
        "number_operands": 15,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 29,
        "loc": 42,
        "lloc": 13,
        "mi": 110.58,
        "mIwoC": 62.58,
        "commentWeight": 48,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Entity\\Task",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Cake\\ORM\\Entity"
        ],
        "parents": [
            "Cake\\ORM\\Entity"
        ],
        "lcom": 0,
        "length": 9,
        "vocabulary": 9,
        "volume": 28.53,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 23,
        "loc": 28,
        "lloc": 5,
        "mi": 123.73,
        "mIwoC": 74.43,
        "commentWeight": 49.31,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Entity\\Project",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Cake\\ORM\\Entity"
        ],
        "parents": [
            "Cake\\ORM\\Entity"
        ],
        "lcom": 0,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 20,
        "loc": 25,
        "lloc": 5,
        "mi": 126.31,
        "mIwoC": 77.16,
        "commentWeight": 49.15,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Entity\\TeamsUser",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Cake\\ORM\\Entity"
        ],
        "parents": [
            "Cake\\ORM\\Entity"
        ],
        "lcom": 0,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 20,
        "loc": 25,
        "lloc": 5,
        "mi": 126.31,
        "mIwoC": 77.16,
        "commentWeight": 49.15,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Table\\UsersTable",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validationDefault",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildRules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Cake\\ORM\\Table",
            "parent",
            "Cake\\Validation\\Validator",
            "Cake\\ORM\\RulesChecker"
        ],
        "parents": [
            "Cake\\ORM\\Table"
        ],
        "lcom": 3,
        "length": 87,
        "vocabulary": 28,
        "volume": 418.24,
        "difficulty": 1.57,
        "effort": 658.34,
        "level": 0.64,
        "bugs": 0.14,
        "time": 37,
        "intelligentContent": 265.71,
        "number_operators": 2,
        "number_operands": 85,
        "number_operators_unique": 1,
        "number_operands_unique": 27,
        "cloc": 33,
        "loc": 64,
        "lloc": 31,
        "mi": 93.82,
        "mIwoC": 48.98,
        "commentWeight": 44.84,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 196.2,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 588.6,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Table\\ProjectsTable",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validationDefault",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildRules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Cake\\ORM\\Table",
            "parent",
            "Cake\\Validation\\Validator",
            "Cake\\ORM\\RulesChecker"
        ],
        "parents": [
            "Cake\\ORM\\Table"
        ],
        "lcom": 3,
        "length": 52,
        "vocabulary": 21,
        "volume": 228.4,
        "difficulty": 1.25,
        "effort": 285.5,
        "level": 0.8,
        "bugs": 0.08,
        "time": 16,
        "intelligentContent": 182.72,
        "number_operators": 2,
        "number_operands": 50,
        "number_operators_unique": 1,
        "number_operands_unique": 20,
        "cloc": 34,
        "loc": 60,
        "lloc": 26,
        "mi": 98.45,
        "mIwoC": 52.48,
        "commentWeight": 45.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.19,
        "relativeSystemComplexity": 225.19,
        "totalStructuralComplexity": 675,
        "totalDataComplexity": 0.56,
        "totalSystemComplexity": 675.56,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Table\\TasksTable",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validationDefault",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildRules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Cake\\ORM\\Table",
            "parent",
            "Cake\\Validation\\Validator",
            "Cake\\ORM\\RulesChecker"
        ],
        "parents": [
            "Cake\\ORM\\Table"
        ],
        "lcom": 3,
        "length": 71,
        "vocabulary": 27,
        "volume": 337.6,
        "difficulty": 1.33,
        "effort": 447.97,
        "level": 0.75,
        "bugs": 0.11,
        "time": 25,
        "intelligentContent": 254.42,
        "number_operators": 2,
        "number_operands": 69,
        "number_operators_unique": 1,
        "number_operands_unique": 26,
        "cloc": 33,
        "loc": 63,
        "lloc": 30,
        "mi": 94.97,
        "mIwoC": 49.94,
        "commentWeight": 45.03,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.18,
        "relativeSystemComplexity": 256.18,
        "totalStructuralComplexity": 768,
        "totalDataComplexity": 0.53,
        "totalSystemComplexity": 768.53,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Table\\TeamsTable",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validationDefault",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildRules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Cake\\ORM\\Table",
            "parent",
            "Cake\\Validation\\Validator",
            "Cake\\ORM\\RulesChecker"
        ],
        "parents": [
            "Cake\\ORM\\Table"
        ],
        "lcom": 3,
        "length": 41,
        "vocabulary": 19,
        "volume": 174.17,
        "difficulty": 1.08,
        "effort": 188.68,
        "level": 0.92,
        "bugs": 0.06,
        "time": 10,
        "intelligentContent": 160.77,
        "number_operators": 2,
        "number_operands": 39,
        "number_operators_unique": 1,
        "number_operands_unique": 18,
        "cloc": 32,
        "loc": 56,
        "lloc": 24,
        "mi": 100.12,
        "mIwoC": 54.07,
        "commentWeight": 46.06,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.21,
        "relativeSystemComplexity": 169.21,
        "totalStructuralComplexity": 507,
        "totalDataComplexity": 0.64,
        "totalSystemComplexity": 507.64,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Table\\TeamsUsersTable",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validationDefault",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildRules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Cake\\ORM\\Table",
            "parent",
            "Cake\\Validation\\Validator",
            "Cake\\ORM\\RulesChecker"
        ],
        "parents": [
            "Cake\\ORM\\Table"
        ],
        "lcom": 3,
        "length": 45,
        "vocabulary": 17,
        "volume": 183.94,
        "difficulty": 1.34,
        "effort": 247.16,
        "level": 0.74,
        "bugs": 0.06,
        "time": 14,
        "intelligentContent": 136.88,
        "number_operators": 2,
        "number_operands": 43,
        "number_operators_unique": 1,
        "number_operands_unique": 16,
        "cloc": 33,
        "loc": 58,
        "lloc": 25,
        "mi": 99.52,
        "mIwoC": 53.51,
        "commentWeight": 46.01,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.21,
        "relativeSystemComplexity": 169.21,
        "totalStructuralComplexity": 507,
        "totalDataComplexity": 0.64,
        "totalSystemComplexity": 507.64,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Model\\Table\\TasksUsersTable",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validationDefault",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildRules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Cake\\ORM\\Table",
            "parent",
            "Cake\\Validation\\Validator",
            "Cake\\ORM\\RulesChecker"
        ],
        "parents": [
            "Cake\\ORM\\Table"
        ],
        "lcom": 3,
        "length": 38,
        "vocabulary": 15,
        "volume": 148.46,
        "difficulty": 1.29,
        "effort": 190.88,
        "level": 0.78,
        "bugs": 0.05,
        "time": 11,
        "intelligentContent": 115.47,
        "number_operators": 2,
        "number_operands": 36,
        "number_operators_unique": 1,
        "number_operands_unique": 14,
        "cloc": 33,
        "loc": 57,
        "lloc": 24,
        "mi": 100.76,
        "mIwoC": 54.55,
        "commentWeight": 46.21,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.3,
        "relativeSystemComplexity": 81.3,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 0.9,
        "totalSystemComplexity": 243.9,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\View\\AppView",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Cake\\View\\View"
        ],
        "parents": [
            "Cake\\View\\View"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0,
        "effort": 0,
        "level": 1.67,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 118.32,
        "mIwoC": 71.04,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\View\\AjaxView",
        "interface": false,
        "methods": [
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\View\\AppView",
            "parent"
        ],
        "parents": [
            "App\\View\\AppView"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 1,
        "effort": 7.92,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 7.92,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 17,
        "loc": 27,
        "lloc": 10,
        "mi": 118.87,
        "mIwoC": 71.76,
        "commentWeight": 47.11,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Console\\Installer",
        "interface": false,
        "methods": [
            {
                "name": "postInstall",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createAppConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createWritableDirectories",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setFolderPermissions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setSecuritySalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setSecuritySaltInFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setAppNameInFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 11,
        "ccnMethodMax": 4,
        "externals": [
            "Composer\\Script\\Event",
            "static",
            "static",
            "Exception",
            "static",
            "static",
            "static",
            "Cake\\Codeception\\Console\\Installer",
            "Cake\\Utility\\Security",
            "static"
        ],
        "parents": [],
        "lcom": 7,
        "length": 265,
        "vocabulary": 75,
        "volume": 1650.64,
        "difficulty": 10.19,
        "effort": 16821.93,
        "level": 0.1,
        "bugs": 0.55,
        "time": 935,
        "intelligentContent": 161.97,
        "number_operators": 67,
        "number_operands": 198,
        "number_operators_unique": 7,
        "number_operands_unique": 68,
        "cloc": 65,
        "loc": 181,
        "lloc": 116,
        "mi": 70.99,
        "mIwoC": 30.96,
        "commentWeight": 40.03,
        "kanDefect": 1.52,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.05,
        "relativeSystemComplexity": 50.05,
        "totalStructuralComplexity": 343,
        "totalDataComplexity": 7.38,
        "totalSystemComplexity": 350.38,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    }
]